---
title: ""
format: 
    dashboard:
        orientation: columns
        fontsize: 12
        logo: BSOLICB.png
        theme: cosmo
        embed-resources: true
        nav-buttons:
            - icon: arrow-left-circle
              href: ParamedicsAnalysis.html

execute:
    enabled: true
project:
  output-dir: output
---

::: {.card title="**How to Interact with the Visuals?**" fill=false}


1. *Zooming*: Click and drag to select a specific area of the chart to zoom into for a closer look. Double-click to zoom back out.
2. *Panning*: Click on the pan button (it looks like a hand or a cross with arrows) in the graph's toolbar, then click and drag to move around the graph.
3. *Hover*: Move your mouse pointer over the bars to see additional information such as exact values or categories. A small tooltip will appear with the data.
4. *Resizing*: You can also click on the corners or edges of the graph to resize it within the window.
5. *Toolbar*: The toolbar, usually found at the top right of the graph, contains tools to manipulate the graph's view. Here's what each button does:
   - The camera icon allows you to download the graph.
   - The home icon resets the graph to its initial state.
   - The magnifying glass icons are for zooming in and out.
6. *Resetting the Graph*: If you've changed the graph view and want to return to the original view, click on the 'Home' button in the toolbar.

:::

:::{.card title="**How to Interact with the Data Table?**" fill=false}

1. *Searching*: Use the 'Search' box to filter the table entries. As you type, the table will dynamically display only the rows that contain your search keyword.
2. *Sorting*: Click on any column header to sort the table by that column. Click once for ascending order, and click again for descending order.
3. *Changing Number of Entries Displayed*: You can change how many entries you view at a time by selecting a number from the 'Show [number] entries' dropdown menu, which typically appears above the table on the left-hand side.
4. *Copying, Excel, PDF*: Use the buttons located typically above the table on the right-hand side to copy data to the clipboard, export the table to an Excel file, or save the table as a PDF.
5. *Paging*: Navigate to subsequent pages by clicking on the page numbers. If the data table is not displayed instantly, click the 'Data' tab twice.

:::



